//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace ZGZY.Model
{
    public partial class CqcDBEntities : ObjectContext
    {
        public const string ConnectionString = "name=CqcDBEntities";
        public const string ContainerName = "CqcDBEntities";
    
        #region Constructors
    
        public CqcDBEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public CqcDBEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public CqcDBEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<cust> cust
        {
            get { return _cust  ?? (_cust = CreateObjectSet<cust>("cust")); }
        }
        private ObjectSet<cust> _cust;
    
        public ObjectSet<employee> employee
        {
            get { return _employee  ?? (_employee = CreateObjectSet<employee>("employee")); }
        }
        private ObjectSet<employee> _employee;
    
        public ObjectSet<ordb> ordb
        {
            get { return _ordb  ?? (_ordb = CreateObjectSet<ordb>("ordb")); }
        }
        private ObjectSet<ordb> _ordb;
    
        public ObjectSet<ordc> ordc
        {
            get { return _ordc  ?? (_ordc = CreateObjectSet<ordc>("ordc")); }
        }
        private ObjectSet<ordc> _ordc;
    
        public ObjectSet<ordh> ordh
        {
            get { return _ordh  ?? (_ordh = CreateObjectSet<ordh>("ordh")); }
        }
        private ObjectSet<ordh> _ordh;
    
        public ObjectSet<fileupload> fileuploads
        {
            get { return _fileuploads  ?? (_fileuploads = CreateObjectSet<fileupload>("fileuploads")); }
        }
        private ObjectSet<fileupload> _fileuploads;

        #endregion
    }
}
