//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ZGZY.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(employee))]
    public partial class cust
    {
        #region Primitive Properties
        [DataMember]
        public virtual string compid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string custid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string longname
        {
            get;
            set;
        }
        [DataMember]
        public virtual string shortname
        {
            get;
            set;
        }
        [DataMember]
        public virtual string addr
        {
            get;
            set;
        }
        [DataMember]
        public virtual string tel
        {
            get;
            set;
        }
        [DataMember]
        public virtual string fax
        {
            get;
            set;
        }
        [DataMember]
        public virtual string invaddr
        {
            get;
            set;
        }
        [DataMember]
        public virtual string uninum
        {
            get;
            set;
        }
        [DataMember]
        public virtual string director
        {
            get;
            set;
        }
        [DataMember]
        public virtual string dbbcall
        {
            get;
            set;
        }
        [DataMember]
        public virtual string dmotel
        {
            get;
            set;
        }
        [DataMember]
        public virtual string contack
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cbbcall
        {
            get;
            set;
        }
        [DataMember]
        public virtual string taxtype
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> taxrad
        {
            get;
            set;
        }
        [DataMember]
        public virtual string crlevel
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> cust11
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> cust12
        {
            get;
            set;
        }
        [DataMember]
        public virtual string updid
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> updtime
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cmotel
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> actdebit
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> actreck
        {
            get;
            set;
        }
        [DataMember]
        public virtual string invname
        {
            get;
            set;
        }
        [DataMember]
        public virtual string par1
        {
            get;
            set;
        }
        [DataMember]
        public virtual string par2
        {
            get;
            set;
        }
        [DataMember]
        public virtual string par3
        {
            get;
            set;
        }
        [DataMember]
        public virtual string par4
        {
            get;
            set;
        }
        [DataMember]
        public virtual string par5
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> cust10
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> cust30
        {
            get;
            set;
        }
        [DataMember]
        public virtual string custtype
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> cust33
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> cust34
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> cust35
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust36
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> cust37
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust38
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust39
        {
            get;
            set;
        }
        [DataMember]
        public virtual string tel2
        {
            get;
            set;
        }
        [DataMember]
        public virtual string motel
        {
            get;
            set;
        }
        [DataMember]
        public virtual string bbcall
        {
            get;
            set;
        }
        [DataMember]
        public virtual string email
        {
            get;
            set;
        }
        [DataMember]
        public virtual string postid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string code
        {
            get;
            set;
        }
        [DataMember]
        public virtual string tradcode
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> cust13
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust14
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust15
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust16
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust17
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust18
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust19
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust20
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust21
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust22
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust23
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust24
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> cust25
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> cust26
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust27
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust28
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust29
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cust31
        {
            get;
            set;
        }
        [DataMember]
        public virtual string otherbid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string useing
        {
            get;
            set;
        }
        [DataMember]
        public virtual string faxh
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> cust40
        {
            get;
            set;
        }
        [DataMember]
        public virtual string bank10
        {
            get;
            set;
        }
        [DataMember]
        public virtual string tmpempid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string taxregno
        {
            get;
            set;
        }
        [DataMember]
        public virtual string bizlicence
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual employee employee
        {
            get { return _employee; }
            set
            {
                if (!ReferenceEquals(_employee, value))
                {
                    var previousValue = _employee;
                    _employee = value;
                    Fixupemployee(previousValue);
                }
            }
        }
        private employee _employee;

        #endregion
        #region Association Fixup
    
        private void Fixupemployee(employee previousValue)
        {
            if (previousValue != null && previousValue.cust.Contains(this))
            {
                previousValue.cust.Remove(this);
            }
    
            if (employee != null)
            {
                if (!employee.cust.Contains(this))
                {
                    employee.cust.Add(this);
                }
            }
        }

        #endregion
    }
}
