//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ZGZY.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(cust))]
    public partial class employee
    {
        #region Primitive Properties
        [DataMember]
        public virtual string compid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string empid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string deptid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string empname
        {
            get;
            set;
        }
        [DataMember]
        public virtual string addr
        {
            get;
            set;
        }
        [DataMember]
        public virtual string tel
        {
            get;
            set;
        }
        [DataMember]
        public virtual string motel
        {
            get;
            set;
        }
        [DataMember]
        public virtual string bbcall
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp11
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp12
        {
            get;
            set;
        }
        [DataMember]
        public virtual string updid
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> updtime
        {
            get;
            set;
        }
        [DataMember]
        public virtual string jobflag
        {
            get;
            set;
        }
        [DataMember]
        public virtual string posid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string securid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string birthday
        {
            get;
            set;
        }
        [DataMember]
        public virtual string stype
        {
            get;
            set;
        }
        [DataMember]
        public virtual string bloodtype
        {
            get;
            set;
        }
        [DataMember]
        public virtual string addr2
        {
            get;
            set;
        }
        [DataMember]
        public virtual string married
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp21
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp22
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp23
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp24
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp25
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<short> emp31
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<short> emp32
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp33
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp34
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp35
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp36
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp37
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp38
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<short> emp39
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp40
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> emp50
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> emp51
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> emp52
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> emp53
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> emp54
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> emp55
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> emp56
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> emp57
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> emp58
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> emp59
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cardid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emptype
        {
            get;
            set;
        }
        [DataMember]
        public virtual string email
        {
            get;
            set;
        }
        [DataMember]
        public virtual string contack
        {
            get;
            set;
        }
        [DataMember]
        public virtual string postid
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> grade
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> rank
        {
            get;
            set;
        }
        [DataMember]
        public virtual string insrdate
        {
            get;
            set;
        }
        [DataMember]
        public virtual string bdate
        {
            get;
            set;
        }
        [DataMember]
        public virtual string cardno
        {
            get;
            set;
        }
        [DataMember]
        public virtual string rdate
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ldate
        {
            get;
            set;
        }
        [DataMember]
        public virtual string bankid
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> insrid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string account
        {
            get;
            set;
        }
        [DataMember]
        public virtual string memo
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> people
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> tax
        {
            get;
            set;
        }
        [DataMember]
        public virtual string dorn
        {
            get;
            set;
        }
        [DataMember]
        public virtual string useing
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> tiket
        {
            get;
            set;
        }
        [DataMember]
        public virtual string brithday
        {
            get;
            set;
        }
        [DataMember]
        public virtual string carid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string identityno
        {
            get;
            set;
        }
        [DataMember]
        public virtual string factid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp60
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp61
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp62
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp63
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp64
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp65
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp66
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp67
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp68
        {
            get;
            set;
        }
        [DataMember]
        public virtual string emp69
        {
            get;
            set;
        }
        [DataMember]
        public virtual string chk
        {
            get;
            set;
        }
        [DataMember]
        public virtual byte[] pic1
        {
            get;
            set;
        }
        [DataMember]
        public virtual byte[] rowver
        {
            get;
            set;
        }
        [DataMember]
        public virtual byte[] pic2
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<cust> cust
        {
            get
            {
                if (_cust == null)
                {
                    var newCollection = new FixupCollection<cust>();
                    newCollection.CollectionChanged += Fixupcust;
                    _cust = newCollection;
                }
                return _cust;
            }
            set
            {
                if (!ReferenceEquals(_cust, value))
                {
                    var previousValue = _cust as FixupCollection<cust>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupcust;
                    }
                    _cust = value;
                    var newValue = value as FixupCollection<cust>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupcust;
                    }
                }
            }
        }
        private ICollection<cust> _cust;

        #endregion
        #region Association Fixup
    
        private void Fixupcust(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (cust item in e.NewItems)
                {
                    item.employee = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (cust item in e.OldItems)
                {
                    if (ReferenceEquals(item.employee, this))
                    {
                        item.employee = null;
                    }
                }
            }
        }

        #endregion
    }
}
