//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ZGZY.Model
{
    [DataContract(IsReference = true)]
    public partial class fileupload
    {
        #region Primitive Properties
        [DataMember]
        public virtual long id
        {
            get;
            set;
        }
        [DataMember]
        public virtual string compid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string factid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string filename
        {
            get;
            set;
        }
        [DataMember]
        public virtual string filetype
        {
            get;
            set;
        }
        [DataMember]
        public virtual string address
        {
            get;
            set;
        }

        #endregion
    }
}
