//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ZGZY.Model
{
    [DataContract(IsReference = true)]
    public partial class ordb
    {
        #region Primitive Properties
        [DataMember]
        public virtual string compid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string formulaid
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> qty
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> uniprice
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordb11
        {
            get;
            set;
        }
        [DataMember]
        public virtual string updid
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> updtime
        {
            get;
            set;
        }
        [DataMember]
        public virtual string stgid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string strength
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> ordb12
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> ordb13
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> ordb14
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> stdprice
        {
            get;
            set;
        }
        [DataMember]
        public virtual string chgpondtype
        {
            get;
            set;
        }
        [DataMember]
        public virtual string strengthbase
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> chgpercent
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> diffprice
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> nprice
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> fprice
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> sprice
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> lprice
        {
            get;
            set;
        }
        [DataMember]
        public virtual string pdefymtype
        {
            get;
            set;
        }
        [DataMember]
        public virtual string pdefym
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> pdefymnum
        {
            get;
            set;
        }
        [DataMember]
        public virtual string useing
        {
            get;
            set;
        }
        [DataMember]
        public virtual string factid
        {
            get;
            set;
        }
        [DataMember]
        public virtual byte[] rowver
        {
            get;
            set;
        }

        #endregion
    }
}
