//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ZGZY.Model
{
    [DataContract(IsReference = false)]
    public partial class ordc
    {
        #region Primitive Properties
        [DataMember]
        public virtual string compid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string addid
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> addmoney
        {
            get;
            set;
        }
        [DataMember]
        public virtual string updid
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> updtime
        {
            get;
            set;
        }
        [DataMember]
        public virtual string memo
        {
            get;
            set;
        }
        [DataMember]
        public virtual string useing
        {
            get;
            set;
        }
        [DataMember]
        public virtual string factid
        {
            get;
            set;
        }

        #endregion
    }
}
