//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ZGZY.Model
{
    [DataContract(IsReference = true)]
    public partial class ordh
    {
        #region Primitive Properties
        [DataMember]
        public virtual string compid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string custid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string empid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string orddate
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh12
        {
            get;
            set;
        }
        [DataMember]
        public virtual string updid
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> updtime
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh13
        {
            get;
            set;
        }
        [DataMember]
        public virtual string memo
        {
            get;
            set;
        }
        [DataMember]
        public virtual string closed
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh11
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh14
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh15
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh16
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh17
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh18
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh19
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh20
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh21
        {
            get;
            set;
        }
        [DataMember]
        public virtual string taxtype
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> taxratio
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> ordcust11
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> ordcust12
        {
            get;
            set;
        }
        [DataMember]
        public virtual string invh12
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> ordh22
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> ordh23
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> ordh24
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> ordh25
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> ordh26
        {
            get;
            set;
        }
        [DataMember]
        public virtual string regid
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> ph13
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> prepay
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh27
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh28
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh29
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh30
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh31
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> ordh32
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh33
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> ordh34
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh35
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh36
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh37
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh38
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh39
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh40
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh41
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordchk
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> maxamt
        {
            get;
            set;
        }
        [DataMember]
        public virtual string bsslump
        {
            get;
            set;
        }
        [DataMember]
        public virtual string bsdiam
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> addslump
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> adddiam
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> addregn
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> addother
        {
            get;
            set;
        }
        [DataMember]
        public virtual string custinvid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string subordid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string sured
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> maxqty
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh42
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh43
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh44
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> longpond
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> shortpond
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> fixedpond
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> addcarprice
        {
            get;
            set;
        }
        [DataMember]
        public virtual string slumphigh
        {
            get;
            set;
        }
        [DataMember]
        public virtual string slumplow
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> slumpdiff
        {
            get;
            set;
        }
        [DataMember]
        public virtual string slumprange
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordtxdate
        {
            get;
            set;
        }
        [DataMember]
        public virtual string workpart
        {
            get;
            set;
        }
        [DataMember]
        public virtual string status
        {
            get;
            set;
        }
        [DataMember]
        public virtual string payment
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> perc01
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> perc02
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> perc03
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> perc04
        {
            get;
            set;
        }
        [DataMember]
        public virtual string tmpempid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordtype
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> ordh45
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> ordh46
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh47
        {
            get;
            set;
        }
        [DataMember]
        public virtual string conid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string chkshiph
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<decimal> empratio
        {
            get;
            set;
        }
        [DataMember]
        public virtual string paydate
        {
            get;
            set;
        }
        [DataMember]
        public virtual string managestatus
        {
            get;
            set;
        }
        [DataMember]
        public virtual string orddesc
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh48
        {
            get;
            set;
        }
        [DataMember]
        public virtual string chkshipdate
        {
            get;
            set;
        }
        [DataMember]
        public virtual string chkshiptime
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordstatus
        {
            get;
            set;
        }
        [DataMember]
        public virtual string factid
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh80
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh81
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh82
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ordh83
        {
            get;
            set;
        }
        [DataMember]
        public virtual byte[] rowver
        {
            get;
            set;
        }

        #endregion
    }
}
